/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:f96c5bdb-c5da-4ab8-87f8-04d266265074",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_PMd7KYlHe",
    "aws_user_pools_web_client_id": "611ar3fgkvs01n3p8tjl20jjuk",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xvjfwqwyqvh55pcybkowmlct4y.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-hrvsb7w33nhebizydtbbtsva6a"
};


export default awsmobile;
